DROP TABLE IF EXISTS film_likes;
DROP TABLE IF EXISTS film_genre;
DROP TABLE IF EXISTS films;
DROP TABLE IF EXISTS genres;
DROP TABLE IF EXISTS mpa;

CREATE TABLE mpa (
    id INTEGER PRIMARY KEY,
    name VARCHAR(100)
);

CREATE TABLE genres (
    id INTEGER PRIMARY KEY,
    name VARCHAR(100)
);

CREATE TABLE films (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    description TEXT,
    release_date DATE,
    duration INTEGER,
    mpa_id INTEGER
);

CREATE TABLE film_genre (
    film_id INTEGER,
    genre_id INTEGER
);

CREATE TABLE film_likes (
    film_id INTEGER,
    user_id INTEGER
);
